[project]
name = "heart-abnormalities-classifier"
version = "0.1.0"
description = ""
authors = [
    {name = "Wiktor Witold Kunicki",email = "wkunicki47@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
